set pythonpath=%pythonpath%;C:\_Liang\models\research;C:\_Liang\models\research\slim
set path=C:\_Liang\protoc-3.5.0-win32\bin;%path%

protoc --python_out=. object_detection\protos\anchor_generator.proto
protoc --python_out=. object_detection\protos\argmax_matcher.proto
protoc --python_out=. object_detection\protos\bipartite_matcher.proto
protoc --python_out=. object_detection\protos\box_coder.proto
protoc --python_out=. object_detection\protos\box_predictor.proto
protoc --python_out=. object_detection\protos\eval.proto
protoc --python_out=. object_detection\protos\faster_rcnn.proto
protoc --python_out=. object_detection\protos\faster_rcnn_box_coder.proto
protoc --python_out=. object_detection\protos\grid_anchor_generator.proto
protoc --python_out=. object_detection\protos\hyperparams.proto
protoc --python_out=. object_detection\protos\image_resizer.proto
protoc --python_out=. object_detection\protos\input_reader.proto
protoc --python_out=. object_detection\protos\keypoint_box_coder.proto
protoc --python_out=. object_detection\protos\losses.proto
protoc --python_out=. object_detection\protos\matcher.proto
protoc --python_out=. object_detection\protos\mean_stddev_box_coder.proto
protoc --python_out=. object_detection\protos\model.proto
protoc --python_out=. object_detection\protos\optimizer.proto
protoc --python_out=. object_detection\protos\pipeline.proto
protoc --python_out=. object_detection\protos\post_processing.proto
protoc --python_out=. object_detection\protos\preprocessor.proto
protoc --python_out=. object_detection\protos\region_similarity_calculator.proto
protoc --python_out=. object_detection\protos\square_box_coder.proto
protoc --python_out=. object_detection\protos\ssd.proto
protoc --python_out=. object_detection\protos\ssd_anchor_generator.proto
protoc --python_out=. object_detection\protos\string_int_label_map.proto
protoc --python_out=. object_detection\protos\train.proto
